title: Bennington Area Robotics
description: Communuty-base youth robotics teams of Bennington VT, supporting STEM education in the greater Bennington area.
url: https://bennington-area-robotics.github.io

# Build settings
markdown: kramdown
